language: python
python:
- '3.6'
sudo: required
dist: trusty
branches:
  only:
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install:
- make install-deps
script:
- make build VERSION=$TRAVIS_TAG
deploy:
- provider: pypi
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
  username: phoenix.lv
  password:
    secure: q6FXwPWbaJkBcELM/btzobGKYyyaf/83bQ/DX8tY7WXMTjz0/LFDFy0LYPC9snQVRPXOBrpuoQClBIfGK3k8wNPcgK2qMt+z727sl8jMXgw7Ih5+U9BsxmgI4fn/HH94iRwccdXtCHSq+RX0jGp0B9sovqHm/g1hgYbvSnSZbTdYc/ATz3a2lC+m/oUrMtENFRynFpfvUuLQzrchSB8wLsrLUhWIAAakxIi9Hai1fmsUSmkyGO7267ULlY6OkjO+ltVX8olOI0hhrqep2UG+DJag1KB/u+/o1SW7eBogxQUlW7QZjHmzIX40L5EobUSSOxfiZxn1IHLklAZ3d0A0MMWKSjhKVktf2XoBs1pGUe/e6YSj5a8uCiqqHIgsooiCyIjblByed5TTP2NpQU83QiTexfOUailuqEKE/YLU/sDyVBg8bQEhsrAR3I3BpAX3LswaK9ZXov33krmXBgTwEJ7HlrmBDXKm4cI2pvvfMf861+/2+9BLtWkpLwz5e8edG7opbBhmXO0ZAuxAfL7XNjPdnG406WFFh/SWXLBqPiTpx8jVY04CZEpm9afn8iQb6U9qo01v8Y75xy5eFaLO1NMWORmbYnLIsIWLW/b6OtOHcA1f2rk+Q5MKMSaLNtkNG8zbNAkpFU/ZLeB5IWvYpntHnKYz4SGoMXnKLANak6k=
